traceoverspeedingalert:
  replicaCount: 1
  meta:
    name: trace-overspeeding-alert-service
    label: trace-overspeeding-alert
    namespace: trace-overspeeding-alert
  rollingupdate:
    maxunavailable: 20%
    maxsurge: 20%
  ports:
    containerport: 80
  httpget:
    port: 80
  http:
    initialdelayseconds: 60
    timeoutseconds: 15
    periodseconds: 30
  limits:
    cpu: "512m"
    memory: "1Gi"
  requests:
    cpu: "256m"
    memory: "500Mi"
  autoscaling:
    minReplicas: 1
    maxReplicas: 1
    targetAverageUtilization: 70
  image:
    repository: 869361712940.dkr.ecr.ap-south-1.amazonaws.com/trace-overspeeding-alert
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: over-27
  service:
    type: ClusterIP
    port: 80
    targetport: 80
  vault:
    env: stag  
  env:
    env: "stag"
    AWS_REGION: "ap-south-1"
    BOOTSTRAP_SERVER: ""
    CLIENT_ID: ""
    GROUP_ID: ""
    SECURITY_PROTOCOL: ""
    SASL_MECHANISM: "S2"
    #SASL_JAAS_CONFIG: ""
    APPLICATION_ID: ""
    INPUT_TOPIC: ""
    ALERT_MANAGER_URL: ""
    ALERT_SQS_URL: ""
    ALERT_REDIS_HOST: ""
