apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.traceoverspeedingalert.meta.name }}
  namespace: {{ .Values.traceoverspeedingalert.meta.namespace }}
  labels:
    app: {{ .Values.traceoverspeedingalert.meta.label }}
spec:
  replicas: {{ .Values.traceoverspeedingalert.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.traceoverspeedingalert.rollingupdate.maxunavailable }}
      maxSurge: {{ .Values.traceoverspeedingalert.rollingupdate.maxsurge }}
  minReadySeconds: {{ .Values.traceoverspeedingalert.rollingupdate.minreadyseconds }}
  selector:
    matchLabels:
      app: {{ .Values.traceoverspeedingalert.meta.label }}
  template:
    metadata:
      name: {{ .Values.traceoverspeedingalert.meta.name }}
      labels:
        app: {{ .Values.traceoverspeedingalert.meta.label }}
    spec:
      containers:
        - name: {{ .Values.traceoverspeedingalert.meta.name }}
          image: "{{ .Values.traceoverspeedingalert.image.repository }}:{{ .Values.traceoverspeedingalert.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.traceoverspeedingalert.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.traceoverspeedingalert.ports.containerport }}
              protocol: TCP
          # command: ["main.js"]  # Add your command here
          # envFrom:
          #   - configMapRef:
          #       name: trace-overspeeding-alert-configmap
            # - secretRef:
            #     name: trace-overspeeding-alert-secret 
          env:
            - name: env
              value: "{{ .Values.traceoverspeedingalert.env.env }}"
            - name: AWS_REGION
              value: "{{ .Values.traceoverspeedingalert.env.AWS_REGION }}"
            - name: BOOTSTRAP_SERVER
              value: "{{ .Values.traceoverspeedingalert.env.BOOTSTRAP_SERVER }}"
            - name: CLIENT_ID
              value: "{{ .Values.traceoverspeedingalert.env.CLIENT_ID }}"
            - name: GROUP_ID
              value: "{{ .Values.traceoverspeedingalert.env.GROUP_ID }}"
            - name: SECURITY_PROTOCOL
              value: "{{ .Values.traceoverspeedingalert.env.SECURITY_PROTOCOL }}"
            - name: SASL_MECHANISM
              value: "{{ .Values.traceoverspeedingalert.env.SASL_MECHANISM }}"              
            - name: SASL_JAAS_CONFIG
              value: "" #"{{ .Values.traceoverspeedingalert.env.SASL_JAAS_CONFIG }}"
            - name: APPLICATION_ID
              value: "{{ .Values.traceoverspeedingalert.env.APPLICATION_ID }}"
            - name: INPUT_TOPIC
              value: "{{ .Values.traceoverspeedingalert.env.INPUT_TOPIC }}"
            - name: ALERT_MANAGER_URL
              value: "{{ .Values.traceoverspeedingalert.env.ALERT_MANAGER_URL }}"
            - name: REDIS_HOST
              value: "{{ .Values.traceoverspeedingalert.env.REDIS_HOST }}"
            - name: ALERT_SQS_URL
              value: "{{ .Values.traceoverspeedingalert.env.ALERT_SQS_URL }}"
            - name: ALERT_REDIS_HOST
              value: "{{ .Values.traceoverspeedingalert.env.ALERT_REDIS_HOST }}"             
          resources:
            requests:
              cpu: {{ .Values.traceoverspeedingalert.requests.cpu }}
              memory: {{ .Values.traceoverspeedingalert.requests.memory }}
            limits:
              cpu: {{ .Values.traceoverspeedingalert.limits.cpu }}
              memory: {{ .Values.traceoverspeedingalert.limits.memory }}
          volumeMounts:  # Add the volume mount here
            - name: pv-overspeed
              mountPath: /app/appdata
      volumes:  # Define the volume here
        - name: pv-overspeed
          persistentVolumeClaim:
            claimName: pvc-overspeed              
      nodeSelector:  # Add the node selector here
        node: app        
      # livenessProbe:
      #   httpGet:
      #     path: /healthz
      #     port: {{ .Values.traceoverspeedingalert.httpget.port }}
      #   initialDelaySeconds: {{ .Values.traceoverspeedingalert.http.initialdelayseconds }}
      #   timeoutSeconds: {{ .Values.traceoverspeedingalert.http.timeoutseconds }}
      #   periodSeconds: {{ .Values.traceoverspeedingalert.http.periodseconds }}
      # readinessProbe:
      #   httpGet:
      #     path: /healthz
      #     port: {{ .Values.traceoverspeedingalert.httpget.port }}
      #   initialDelaySeconds: {{ .Values.traceoverspeedingalert.http.initialdelayseconds }}
      #   timeoutSeconds: {{ .Values.traceoverspeedingalert.http.timeoutseconds }}
      #   periodSeconds: {{ .Values.traceoverspeedingalert.http.periodseconds }}
