apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-example
  namespace: trace-overspeeding-alert
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: trace-overspeeding-alert-secret
  data:
  - secretKey: test
    remoteRef:
      key: kv/secret/{{ .Values.traceoverspeedingalert.vault.env }}/common
      property: test
